#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

domain=$1
subdomain=$2


subdomains=("www" "lb-01" "web-01" "web-02")

if [[ ! -z $subdomain ]]; then
  subdomains=($subdomain)
fi


for sub in "${subdomains[@]}"; do
  dns_info=$(dig +short $sub.$domain | awk '{printf "%-30s %-10s %-15s\n", "'"$sub.$domain"'", $1, $2}')
  if [[ ! -z $dns_info ]]; then
    echo "The subdomain $dns_info"
  fi
